# Generated by Django 5.2.5 on 2025-08-24 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_production_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "speed_factor",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=120)),
                ("volume_x", models.PositiveIntegerField(blank=True, null=True)),
                ("volume_y", models.PositiveIntegerField(blank=True, null=True)),
                ("volume_z", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="component",
            name="base_time_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tempo base (min)"
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="batch_size",
            field=models.PositiveIntegerField(default=1, verbose_name="Qtd por prato"),
        ),
        migrations.AddField(
            model_name="component",
            name="per_plate_time_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tempo por prato (min)"
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="tags_required",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Tags requeridas"
            ),
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "due_date"],
            },
        ),
    ]
